spring:
  application:
    name: datastudio-server
  datasource:
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      pool-name: master-hikari-connection-pool
      connection-timeout: 60000
      maximum-pool-size: 20
      max-lifetime: 1800000
      keepalive-time: 1750000
    url: jdbc:mysql://${MYSQL_MASTER_HOST}:${MYSQL_MASTER_PORT:3306}/data_capture
    username: ${MYSQL_MASTER_USER}
    password: ${MYSQL_MASTER_PASSWORD}
datastudio:
  engine-config:
    artifacts-home: artifacts
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    use-generated-keys: true