plugins {
  id 'java'
  id 'org.springframework.boot'
  id 'io.spring.dependency-management'
}

description = 'datastudio-server'

dependencies {
  implementation project(":datastudio-common")
  implementation 'org.springframework.boot:spring-boot-starter-web'
  implementation 'org.springframework.boot:spring-boot-autoconfigure'
  implementation(libs.hadoop.common) {
    exclude group: "org.slf4j", module: "slf4j-reload4j"
    exclude group: "ch.qos.reload4j", module: "reload4j"
  }
  implementation libs.mybatis.plus
  implementation libs.mybatis.plus.join
  implementation libs.jdbc

  compileOnly libs.lombok

  annotationProcessor libs.lombok
  annotationProcessor libs.mapstruct.processor

  testImplementation 'org.springframework.boot:spring-boot-starter-web-test'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
  testCompileOnly libs.lombok
  testAnnotationProcessor libs.lombok
}

springBoot {
  buildInfo()
}

test {
  useJUnitPlatform()
}
